version: '3'

services:
  app-matta-di-mirko:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
